version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: music-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  minio:
    image: minio/minio
    container_name: music-minio
    ports:
      - "9000:9000" # API port for Spring Boot
      - "9001:9001" # Web UI Console port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: music-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev

  rabbitmq:
    image: rabbitmq:3-management
    container_name: music-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo-data:
  minio-data: