server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/simplymusic
        registration:
          keycloak:
            provider: keycloak
            client-id: simplymusic-frontend
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            client-authentication-method: none
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/simplymusic
  codec:
    max-in-memory-size: 100MB
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      default-filters:
        - TokenRelay
      routes:
        - id: music-service
          uri: lb://SIMPLYMUSIC
          predicates:
            - Path=/api/v1/music/**

        - id: analytics-service
          uri: lb://ANALYTICS-SERVICE
          predicates:
            - Path=/api/v1/analytics/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
